### ISSUE TITLE
Include example source files in GDCC/doc

### ISSUE THREAD

**Issue by 0x7F800000** [DavidPH/GDCC#3]
It would really help to have a few examples. This compiler sounds really great but the documentation is a little dense.

**Comment by DavidPH** [comment]
Would something like this be a useful example of basic usage? https://gist.github.com/DavidPH/89595965a9c8eefb9b35 Is there anything specific that should also be covered? Are the examples too impractical/contrived to be demonstrative? As you might have guessed, documentation is a weakness of mine, but I understand the value of example code to supplement the technical specifications.

**Comment by DavidPH** [comment]
Example code has been made covering extensions for both C and ACS, so I think that satisfies the meat of this issue. I do intend to document ACS deviations and C implementation-defined behavior, but I think that is a separate problem.

To be clear, I do not intend to provide documentation of core language features for either language. C has enough reference material scattered throughout the Internet to bury a small nation. ACS also has documentation and reference material available, and gdcc-acc is targeted at people already using ACS anyway.
